### PR TITLE
Update path to python binary

### PR DESCRIPTION
**Pull request by blak3r2**
Updated two things which may not be universal... I'm not a python developer so you may want to verify.

Followed this link for the :amd64 addition

### CODE REVIEW

**Comment by blak3r2** [comment]
I can confirm that elsewhere in the setup docs you have the path set as i suggested in my pull request.

**Comment by earthgecko** [comment]
Hi Blake

Thanks for the ommision of the bin in the path.

Could you let me know the debian family flavour you are running please.

Some debugging.  It is rare to see the arch appended to the package with : and
not lib64bz2-dev-amd64 so I am wondering are you running a Multiarch set up?
https://wiki.debian.org/Multiarch/HOWTO

Although I have not tested pure Debian, I have had a look at the Debian packages
that I can find too and all Debian and Ubuntu packages I can find relate to
lib64bz2-dev and arch i386, in fact there is no amd64 version or files that I
can find all i386, powerpc, s390 and sparc.

So Ubuntu 14.04 definitely do not like the :amd64 part and I am not running
anything special.

```
~$ sudo apt-get install lib64bz2-dev:amd64
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lib64bz2-dev
gary@mc11:~# 

~$ sudo apt-get install lib64bz2-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
lib64bz2-dev:i386 is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 3 not to upgrade.
gary@mc11:~# 

~$ uname -a
Linux mc11 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

**Comment by blak3r2** [comment]
99% sure it's Ubuntu 14.04. I will update tomorrow.

**Comment by blak3r2** [comment]
```
~$  uname -a
Linux ip-10-0-0-79 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

~$ sudo apt-get install lib64bz2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib64bz2-dev

~$ sudo apt-get install lib64bz2-dev:amd64
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib64bz2-dev
```

Soo... i dunno what i did to get :amd64 working I can't find the page in my history i followed.

**Pull request merged**
